version: 2
jobs:
  build:
    working_directory: ~/live-comments-viewer
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache
      - run:
          name: Install deps
          command: yarn --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
